/*insert INTO DEPARTMENT(DEPARTMENTID, ORGANIZATIONID, NAME) VALUES ('0','0','HR');
insert INTO ORGANIZATION(ORGANIZATIONID, NAME, ADDRESS) VALUES ('0','TCS','1 TOMATO WAY');

insert INTO EMPLOYEE(ID, ORGANIZATIONID, DEPARTMENTID, NAME, AGE, POSITION) VALUES ('0','0','0','JAMES','22','CEO');*/

SELECT * FROM EMPLOYEE